### ISSUE TITLE
As an admin, I'd like to look at an Attendee record and know what panels apps they are associated with

### ISSUE THREAD

**Issue by binary1230** [magfest/panels#103]
if looking at the /uber/registration/form page, it would be cool if someone is associated with a panel app if it told you.  something like this;

![image](https://user-images.githubusercontent.com/5413064/28849407-de47933e-76e4-11e7-8c53-d53ae043ccc5.png)

situation that just happened:  Someone got an email saying "Hey congrats you're a panelist, please fill in your new placeholder badge" and they didn't know they had been named as a co-presenter of the panel.  From the email and attendee record, Gerardo wasn't able to easily figure out what panel they were associated with, and we could only get it by looking at the global feed of database changes, which is very user unfriendly.

I'd say low priority, but nice to have.

might need https://github.com/magfest/panels/issues/61 for this

**Comment by RobRuana** [comment]
A very auspicious time for you to post this issue! I am deep in the panels code, so I may be able to roll this into my current work!

**Comment by kitsuta** [comment]
I don't think this can be done through any one plugin. I think we need to upgrade the core plugin to be able to consume and print fields from plugins before this is possible. I have a plan for this even!
