### ISSUE TITLE
Check for possible duplicates

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/panels#11]
When a panel is accepted, it shows the admin all of the badges that are about to be created.  However, it does NOT show possible matches.  In other words, if someone is already in the system as "John Smith" but they put "Johnathan Smith" on their panel application, a duplicate badge will be created.

When we show a badge about to be created, we should ALSO show "soft-matches".  This probably means:
- people with the same email address and same last name but different first name
- people with different email addresses but the same first and last name

Anything else is probably overkill.

**Comment by bds002** [comment]
This should be system wise as MIVS judges and things has similar issues I believe. 

Step 1 on any NON-Registration front end badge creation (or for Registration for that matter as well) should be to check for possible duplicates.

**Comment by EliAndrewC** [comment]
> Agreed; I'll file a similar ticket in the MIVS codebase and link to this one.

This should be system wise as MIVS judges and things has similar issues I believe.

> Step 1 on any NON-Registration front end badge creation (or for Registration for that matter as well) should be to check for possible duplicates.

Yeah, we really need to be better about doing these checks everywhere.  Right now if an admin creates a placeholder registration for someone already in the system, it doesn't give so much as a warning even if they enter EXACTLY the same information.

**Comment by EliAndrewC** [comment]
Closing as a dupe.
