### ISSUE TITLE
Bad panels application validation logic

### ISSUE THREAD

**Issue by RobRuana** [magfest/panels#118]
The following line adds the newly created model objects to the database session (note that this happens inside the `process_panel_app()` method): https://github.com/magfest/panels/blob/f6f87ac286851e5d76d76edbb01535364a2b5a24/panels/site_sections/panel_applications.py#L127

However, one additional validation is performed *after* the items are added to the session (note that this happens immediately after the call to `process_panel_app()`): https://github.com/magfest/panels/blob/f6f87ac286851e5d76d76edbb01535364a2b5a24/panels/site_sections/panel_applications.py#L64

This means that the panel application could be added to the session and saved to the database while in an invalid state. The above validation should be moved to *before* the call to `process_panel_app()`.

**Comment by kitsuta** [comment]
Whoa, that's a really good point. I can't believe I missed this!

**Comment by RobRuana** [comment]
To be fair, I missed it too! I reviewed that pull request and approved it 😀

Seriously though, this is super subtle. I poured over that code for hours before I noticed.
