### ISSUE TITLE
Intermittent email validation failures for Other Panelists

### ISSUE THREAD

**Issue by RobRuana** [magfest/panels#119]
This is a tricky one, because we haven't been able to reproduce it at all. There have been two separate reports, both of which came in during the afternoon and evening of October 2, 2017. Same issue described in both reports. While attempting to submit a panels application with "Other Panelists", an validation error is reported for the "Other Panelist", even though in both cases a valid email was provided.

There has been speculation that this was caused by a bad copy/paste that somehow included invalid (non-printable) characters.

While investigating this issue, I ran into another (potentially related?) issue: https://github.com/magfest/panels/issues/118

I don't know if these issues are related, but maybe?

**Comment by kitsuta** [comment]
Of note here is that the email validation uses a regexp, which... :|

**Comment by RobRuana** [comment]
Yeah, email regex is not ideal. But the email addresses they were using should have been fine 😅

**Comment by kitsuta** [comment]
Oh for sure. :( Not being able to reproduce the problem is really confusing; I even tried to use almost all the same data someone tried to submit their panel with.

If we're lucky, it's some bug that we happened to magically fix after the 2nd.
