### ISSUE TITLE
Be able to turn off specific emails for specific panels

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/panels#54]
I was talking to Tom about how they handle special "unique snowflake" panels, and sometimes we might want a particular panel to NOT get particular automated emails, because they need to be manually emailed with special instructions and such.

We're not tackling that this year because we need to figure out exactly what we want, e.g.
- should we be turning off ALL automated emails for a panel, or only specific ones?
- should that be a checkbox that gets checked/unchecked or a special status that implies other things?
 - etc

**Comment by RobRuana** [comment]
Seems related to https://github.com/magfest/panels/issues/83

**Comment by RobRuana** [comment]
Closing as duplicate/overcome by #83
