### ISSUE TITLE
Collect better Tech Ops info in the panel application form

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/panels#82]
We've found over the past few years that panelists are *really* bad at providing the necessary information about their technical needs.  For example, it's common for them to simply say they need "an adaptor" with no additional context.

We don't currently have a solid idea of what questions we need to ask, but we should probably have an entire section of the form devoted to their technical needs.  It can ask them a series of questions, such as "Are you bringing a laptop?" and then provide the subsequent questions as appropriate.

We'll need to ask Tech Ops for a set of information that would be useful to them and then extrapolate the list of questions that will wring that out of the applicants.

**Comment by kitsuta** [comment]
Silly question, but don't we currently do this by directly them to a google spreadsheet? Could we gather the necessary questions from that spreadsheet?

**Comment by EliAndrewC** [comment]
> Silly question, but don't we currently do this by directly them to a google spreadsheet? Could we gather the necessary questions from that spreadsheet?

No, we currently gather that information as part of the Panel Application form.  This issue is to expand the questions we ask as part of that form.

(I believe there are other departments which do the Google Spreadsheet thing you're talking about.)

**Comment by kitsuta** [comment]
Oooh yeah, I'm thinking of the department head checklist I think. Whoops.

**Comment by kitsuta** [comment]
Oh, whoops! We never got a definition of exactly what we need to put on the form!

**Comment by jcooter** [comment]
Running panels tech for TMG, I asked everyone two questions when they showed up: are you hooking something up to the projector (if so, what are you hooking up to the projector), and are you hooking anything up that needs sound (laptop, game console, mp3 player, etc).

If people are hooking up a laptop, asking the question "does your laptop have HDMI output" is usually a good enough question to narrow down whether any adapters are needed.

On the audio side, most commonly people will need either stereo RCA or headphone 1/8".  If they need something other than that, we need an adapter.

Also, it helps a lot by understanding what the panelist is going to be doing on-stage - for instance if they say something like "I'm going to be doing a lot of drawing at the podium" we might get them a document camera to be able to show that - they wouldn't know to ask for something like that, but we can intuit a lot.

**Comment by ID4120** [comment]
Agreed about asking the panelists for what they're trying to do more so than specifics of what they need. Many simply aren't familiar with the terminology or the implications of what specifically they have/will need. Unfortunately, the reality is that many instances will exist where a conversation will be necessary to figure out exactly what we'll need to get them running. We should definitely ask about network requirements, whether they'll have content to display on the projection screens, and whether they'll have any audio to play through the speakers.
