### ISSUE TITLE
As an admin, I want to see a subset of rooms while editing the schedule

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/panels#85]
Panel admins only care about panel rooms.  It would make their lives a lot easier if they could toggle which rooms are being displayed while making edits to the schedule.

A simple version of this could be a "Show only panel rooms" checkbox.  A more complicated version of this could be giving admins full control over which rooms are shown.  Ideally we could do both, e.g. have some shortcuts ("Music Rooms", "Tabletop Rooms", "Panel Rooms") but also offer full control.

**Comment by kitsuta** [comment]
Other ideas for filters/shortcuts:
Setup and teardown rooms
Accessible rooms
Room by floor number (particularly the 2nd floor and the floor on the same level as staff suite)
Suites vs single-bed vs 2-bed rooms
