### ISSUE TITLE
Additional form fields on the Panel Application

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/panels#88]
Rather than file separate issues for each individual form field, I'm listing all of the simple ones here:

1) "Additional Information you think we need" (we can indicate that this can include information not for public consumption, but merely things that the event needs to know)

2) "Expected Panel Length" should change from a freeform field to a dropdown with the following options:
- 60 minutes
- 90 minutes
- 120 minutes
- Other

If they select anything other than 60 minutes, show another field asking "Why do you need the extra time?"  We should make it clear on the form that longer panels are allowed but discouraged unless the panel really needs the extra time.

3) "Does your room need tables set up for participation?"  If they select "Yes" then we'll show an extra field indicating what table needs they have.

4) "Does your event require attendees to pay an upfront cost of materials for hands-on activities?"  If they select "Yes" then we'll show an extra field asking what materials will be provided and what cost they'll be asking for.

5) Ask about whether they're interested in having their panel live-streamed; have this be a dropdown with:
- Yes (add a note saying this doesn't guarantee that it WILL be stream)
- No
- Don't care

**Comment by RobRuana** [comment]
I got a fair bit of work done on this one! Should have a pull request by tomorrow.

**Comment by kitsuta** [comment]
Uh.. Rob? I already did this. https://github.com/magfest/panels/pull/96
