### ISSUE TITLE
Add new "Panel Categories" multiselect to both applications and events

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/panels#89]
The panel application form has a "Type of Panel" dropdown.  We'd like to replace that with a multiselect group of checkboxes with a set of predefined categories.

The panel folks will need to let us know what those categories should be.

One of the options should be "Other" which allows them to specify a freeform description.

Events should have this same set of checkboxes.  It should be required for panel applications but optional for events.

The panel folks would also like a report showing the overlaps of simultaneous events with the same categories.  For example, the panel department likes to avoid having two different "Game Show" events at the same time.  This should be allowed but simply be reported.

**Comment by kitsuta** [comment]
Could you specify the difference between 'panels' and 'events'? I thought those terms were interchangeable -- is this just a part of this plugin I don't know about?

**Comment by EliAndrewC** [comment]
Good point!

All rooms on the schedule have "Events".  However, there are a subset of rooms which are designated as "Panel Rooms" in our config.  Unlike most of our other areas, the events in these rooms are largely populated by the submissions to the Panel Application form.

When we refer to "panels" what we usually mean is "the subset of events which started as a Panel Application which then got approved and put on the schedule".

**Comment by patrickburden** [comment]
Shortlist (will update if revised):

Types of Panels (Choose 1)

Lecture, Group Discussion with Moderator, Q&A, Gameshow, Workshop, Learn to Play, Audience Participation, Physical Activity (either group participation or performance), Comedy Performance, Music Performance, Podcast/Vodcast Recording, Karaoke/Sing a Long, Movie Screening, Other

Subcategories (Choose up to 4)

Historical recap, Design, Industry, voice acting, physical acting, text adventure, Jackbox, Nostalgia, Entertainment, Video Production, Music Production, Game Design, Game Theory, Crafting, Computing, Programming, Music Theory, Movies, Literature, Sci Fi, Creative Writing, Tabletop Gaming, Role Playing, Serious Gaming, Live Streaming, Speed Running, Randomizer, Tournament

**Comment by RobRuana** [comment]
Ok, because "Types of Panels" is limited to "Choose 1", it will remain a dropdown instead of a multiselect.

**Comment by RobRuana** [comment]
Ok, just got an update on this issue in slack...

The "Types of Panels" will be as described above. The "Subcategories" will be dropped altogether.

Additionally, the checkbox that says "Does your room need tables set up for participation?" should say "Would your panel benefit from a different setup from our normal panel rooms (for instance, tables for people to work on?) " with the subtext of "Our ability to reconfigure main panel rooms is very limited, but we have some alternative spaces that might be better suited for specific needs."
