### ISSUE TITLE
Unique email subjects for panel emails

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/panels#9]
Tom said the following in an email:

> The flurry of replies I'm getting to acceptance letters from various panelists is all coming to my inbox in one increasingly unwieldy thread.  I assume this is because they all have the same subject line?
> 
> Can we make it so that in the future, the name of the panel is included in the subject line of the auto-email, so any replies will come in separately?

This is a bigger change than what we can do for this year (because of how our email system works right now), but it's definitely a reasonable request, and we've had similar requests from other departments.

**Comment by namalic** [comment]
Instead of approving and declining individual panels, checkboxes with the option to decline or accept marked panels would be nice.

**Comment by namalic** [comment]
Change the update notice at the top so it does not overlap navigation options

add panels voting, email approval, and github email templates to RAMS navigation

**Comment by EliAndrewC** [comment]
> Instead of approving and declining individual panels, checkboxes with the option to decline or accept marked panels would be nice.

Checkboxes to decline or waitlist would definitely be easy and have low impact, but I'm concerned about doing the same thing for accepting.  Marking a panel as accepted creates a set of panelist badges for the applicants, which is something I thought we'd want to be more explicit about, by showing the admin "this is what is about to happen".  If I'm wrong and people are just like, "I'm sure whatever it's going to do is fine" then I can make that more automatic as well.

**Comment by EliAndrewC** [comment]
Closing as a duplicate of #23
