### ISSUE TITLE
Request extra information about each panelist

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/panels#90]
We currently ask for name, email, and phone number for each panelist.

The panels department has other information they'd sometimes like to collect (but which should probably be optional), such as social media info, what position that person has within the industry, etc.

The panels department will need to let us know exactly what information they want to collect before we can implement this.  Until that time, this issue is mostly a placeholder.

**Comment by patrickburden** [comment]
Some information: 

Contact Info

Social Media: Facebook, Twitter, Instagram, LinkedIn
Contact Info: First Name, Last Name, Phone Number, Email, Preference of communication
Credentials: Occupation, Website, Open Space to include any relevant information
